environment: development
chdir: /Users/stephenboak/Sites/stephenboak
address: 127.0.0.1
port: 4567
pid: /Users/stephenboak/Sites/stephenboak/tmp/thin.pid
rackup: /Users/stephenboak/Sites/stephenboak/thin/config.ru
log: /Users/stephenboak/Sites/stephenboak/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true