environment: development
chdir: /var/www/stephenboak/current/stephenboak
address: www.stephenboak.com
user: root
group: root
port: 80
pid: /var/www/stephenboak/tmp/thin.pid
rackup: /var/www/stephenboak/thin/config.ru
log: /var/www/stephenboak/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true